repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: hatch run +py=3.10 lint:fmt
        language: python
        types: [python]
        pass_filenames: false
        verbose: true
      - id: linter
        name: linter
        entry: hatch run lint:typing
        language: python
        types: [python]
        pass_filenames: false