name: Publish to PyPi
on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build-distribution:
    name: "Build distribution"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout tag/branch"
        uses: "actions/checkout@v3"
      - name: "Setup Python"
        uses: "actions/setup-python@v3"
        with:
          python-version: "3.9"

      - name: "Install build dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt

      - name: "Build wheels & source dist"
        run: |
          hatch build dist

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: source-dist
          path: dist

  PyPi:
    needs: ["build-distribution"]
    name: "Publish to PyPi"
    runs-on: "ubuntu-latest"
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: source-dist
        path: dist

    - name: Publish package to PyPI
      if: startsWith(github.ref, 'refs/tags/')
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt
          hatch publish dist -r main -u __token__ -a ${{ secrets.PYPI_API_TOKEN }}
